#!/usr/bin/env python3.12
"""
Put the technical version of the last commit into read_pressure/version.py

Copy this script to .git/hooks
"""
import git

repo = git.Repo()
version = repo.git.describe('--tags')

with open('read_pressure/version.py', 'w+') as fd:
    fd.write(f'VERSION = "{version}"\n')
    print(f'hooks/post-commit: version={version}')
