#!/usr/bin/env python3.12
"""
Put the technical version of the last commit into read_pressure/version.py

Change git's hook dir to .githooks:
    git config core.hooksPath .githooks
"""
import git
import sys

repo = git.Repo()
version = repo.git.describe('--tags')

with open('read_pressure/version.py', 'w+') as fd:
    fd.write(f'VERSION = "{version}"\n')
    print(f'{sys.argv[0]}: version={version}')
