allow_all_imports: true
apps:
  read_pressure:
    - camera_device:    "camera.ipc_113063893_mainstream"
      image_dir:        "/home/hass/.homeassistant/www/pressure"
      image_file:       "gauge.png"
